// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `LogProgressTableGenerationReportFunction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `report`

Future<bool> precomputedTablesExist({required String precomputedTablesPath}) =>
    RustLib.instance.api.crateApiTableGenerationPrecomputedTablesExist(
        precomputedTablesPath: precomputedTablesPath);

Future<void> savePrecomputedTables(
        {required PrecomputedTablesShared tables, required PathBuf filePath}) =>
    RustLib.instance.api.crateApiTableGenerationSavePrecomputedTables(
        tables: tables, filePath: filePath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PrecomputedTablesShared>>
abstract class PrecomputedTablesShared implements RustOpaqueInterface {}
